source 'https://github.com/SDOSLabs/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_modular_headers!
inhibit_all_warnings!

def shared_pods
	pod 'SDOSFLEX', :path => '../../', :configurations => ['Debug', 'Preproduction'], :inhibit_warnings => false
	pod 'FLEX', :configurations => ['Debug', 'Preproduction']
end

target :SDOSFLEX do
	shared_pods
end
