//  FICHERO AUTOGENERADO - NO MODIFICAR
//  StoryboardConstants.h
//
//  Created by SDOS
//

#import <Foundation/Foundation.h>

extern NSString * const SBNameExampleFLEX;

 //
 // ExampleFLEX.h
 // Generated by seguecode

#pragma once

#import <UIKit/UIKit.h>

#import "DocumentationFLEXViewController.h"

@interface DocumentationFLEXViewController (ExampleFLEX)

@end
@interface UINavigationController (ExampleFLEX)

@end

// Auto generated file - any changes will be lost

#import <Foundation/Foundation.h>

#pragma mark - storyboardNames
extern NSString * const ExampleFLEX;


