//  FICHERO AUTOGENERADO - NO MODIFICAR
//  StoryboardConstants.m
//
//  Created by SDOS
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NSString * const SBNameExampleFLEX = @"ExampleFLEX";

 //
 // ExampleFLEX.m
 // Generated by seguecode


@implementation DocumentationFLEXViewController (ExampleFLEX)

@end
@implementation UINavigationController (ExampleFLEX)

@end

// Auto generated file - any changes will be lost


#pragma mark - storyboardNames
NSString * const ExampleFLEX = @"ExampleFLEX";


